### PR TITLE
Tracking: add tracking on the toggles, bug report submissions, and branch activation buttons

### LINKED ISSUE #74: Add Tracks events
Add Tracks events to actions, such as: 

- Enable/disable autoupdates 
- Choosing a version 
- Enable/disable email
- Submit a bug report

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #74 

This PR adds Tracking to the toggles and branch activation buttons on the Jetpack Beta admin page.
Tracking only happens if one has accepted our ToS, and thus the tracking script is enqueued on that page.

### Testing instructions

1. Enable debug in your browser console: `localStorage.setItem( 'debug', 'dops:analytics' );`
2. Try clicking buttons on a site where Jetpack has never been connected to WordPress.com; you should see nothing.
3. Connect Jetpack to WordPress.com and reload the page.
4. Try clicking the buttons: you should see events being tracked: `jetpack_beta_toggle_autoupdates`, `jetpack_beta_toggle_email_notifications`, `jetpack_beta_activate_branch`, `jetpack_beta_submit_report`, with more details in event props.
5. Check Tracks for your username to see the events coming through.

### CODE REVIEW

File: admin/admin.js [hunk 1]
```diff
@@ -1,132 +1,156 @@
...
+	search_close_link.addEventListener('click', function(event) {
+		hide_section();
+		hide(search_close_link);
+		search_input.value = '';
+		event.preventDefault();
+	});
+
+	// Activate Links
+	each.call(activate_links, function(element, index) {
+		element.addEventListener('click', trackEvent.bind(this, element));
```
Comment (jeherve) [inline admin/admin.js]: Here is one of the changes that matter.

File: admin/admin.js [hunk 2]
```diff
@@ -1,132 +1,156 @@
...
+				event.preventDefault();
+			});
+			element.removeEventListener('click', activate_link_click.bind(this, element));
+			element.classList.add('is-disabled');
+		});
+	}
+
+	// Toggle Links
+	each.call(toggle_links, function(element, index) {
+		element.addEventListener('click', trackEvent.bind(this, element));
```
Comment (jeherve) [inline admin/admin.js]: Here is one of the changes that matter.

File: admin/admin.js [hunk 3]
```diff
@@ -1,132 +1,156 @@
...
+
+	function hide(element) {
+		element.style.display = 'none';
+	}
+
+	function show(element) {
+		element.style.display = '';
+	}
+
+	/**
```
Comment (jeherve) [inline admin/admin.js]: Here is the new function that does most of the work.

File: admin/admin.js (hunk 1 above)
Comment (dereksmart) [reply admin/admin.js]: another approach at separating whitespace changes is to do them in a separate dedicated commit, so then the reviewer could just look at specific commits.

**Comment by dereksmart** [comment]
Looks good! 

I only saw one weird thing, that hitting the toggle button fires 2 events 
image

But the rest seemed to be sent properly. Verified that the event props carried the values as expected, even in the search activations. I also verified the events were received properly by wpcom. 

Also that it respects the TOS option. However, they were still sending when Jetpack was disconnected. If so, it would mean that it's probably Jetpack is doing the same (we don't clear the TOS option on disconnect), so we should look into that separately from the beta plugin context.

**Comment by brbrr** [comment]
It seems that it's not possible to disable auto-updates with this patch. Also, I can confirm the bug Derek mentioned above. 
screencast 2019-07-24 16-47-16

**Comment by jeherve** [comment]
The double tracking should now be fixed, as well as the broken toggles.
