### PR TITLE
Download tags directly from wp.org SVN

### LINKED ISSUE #66: Add ability to run  old versions of Jetpack to test regressions

### LINKED ISSUE #83: Pull tags from wp.org svn
Add an option to download tags (or trunk) from wp.org svn directly. 

This will be a way to actually test the beta that will reach end users.

### PR DESCRIPTION
**Pull request by dereksmart**
Fixes #83 
Fixes #66 

Adds a new search field for wp.org tags/trunk. 

image

It's not very DRY.  I ran into the classic "Should I refactor everything or copy/paste", and decided on the latter. I actually somewhat like the clear distinction between the two searches, even at the expense of some duplicate code. At the same time, maybe I'm just telling myself that because it's easier right now. Any way, I don't see us needing to expand this very often anyway. 

Test: 
- No console errors 
- Activating a stable tag or trunk should reflect properly in all UI
- Should not have any effect on any other selections from the Beta Manifest
- I've decided to hide the toggle when on a tag, so you should not expect to see it when active. 
- It downloads to the `jetpack` directory, as opposed to `jetpack-dev`. 
- Break it however you like. 

Appreciate any thoughts on making it more DRY without a significant refactor. There's a strange existing nomenclature of `branch` vs `pr` vs `tag`, that only sorta makes sense right now, but for the sake of this PR, I would like to leave refactors for future PRs.

### CODE REVIEW

File: jetpack-beta-admin.php [hunk 1]
```diff
@@ -302,6 +302,49 @@ static function show_branch( $header, $branch_key, $branch = null, $section = nu
...
+		?>
+		<div <?php echo $data_tag; ?> " class="dops-foldable-card <?php echo esc_attr( $className ); ?> has-expanded-summary dops-card <?php echo $is_compact; ?>">
+			<div class="dops-foldable-card__header has-border">
+				<span class="dops-foldable-card__main">
+					<div class="dops-foldable-card__header-text">
+						<div class="dops-foldable-card__header-text tag-card-header">Jetpack <?php echo esc_html( $header ); ?></div>
+						<div class="dops-foldable-card__subheader">
+						<?php
+						sprintf(
+							__( 'Official tag <a href="https://plugins.trac.wordpress.org/browser/jetpack/tags/%s" target="_blank">%s</a> downloaded from wp.org', 'jetpack-beta' ),
```
Comment (jeherve) [inline jetpack-beta-admin.php]: How about something like this instead?

```suggestion
							__( 'Public beta (%2$s) <a href="https://plugins.trac.wordpress.org/browser/jetpack/tags/%1$s" target="_blank" rel="">available on WordPress.org</a>', 'jetpack-beta' ),
```

File: jetpack-beta.php [hunk 2]
```diff
@@ -508,6 +516,13 @@ static function get_jetpack_plugin_pretty_version( $is_dev_version = false ) {
 			return 'Latest Stable';
 		}
 
+		if ( 'tags' === $section ) {
+			return sprintf(
+				'Official <a href="https://plugins.trac.wordpress.org/browser/jetpack/tags/%s" target="_blank">tag</a> downloaded from wp.org svn',
```
Comment (jeherve) [inline jetpack-beta.php]:
```suggestion
				__( 'Public beta (<a href="https://plugins.trac.wordpress.org/browser/jetpack/tags/%1$s" target="_blank" rel="">available on WordPress.org</a>', 'jetpack-beta' ),
```

Comment (dereksmart) [reply jetpack-beta.php]: Most of the tags are not beta, but the other suggestions look good!

Comment (jeherve) [reply jetpack-beta.php]: That's a good point, I'll replace with `release`.
