### PR TITLE
Fix/autoupdates to work again

### LINKED ISSUE #36: Getting constant notice that Bleeding Edge is not running the latest version
If I activate the Bleeding Edge branch, I always get a notice about it not running the latest version. 

**Screenshot**

image

**Screencap**

bleedingedge

### LINKED ISSUE #39: Maybe add the ability to autoupdate Bleeding edge and notifiy via email
I'm loving these messages from WordPress Beta Tester:

image

### PR DESCRIPTION
**Pull request by enejb**
Fixes #36
Fixes #39 

Currently autoupdates do not work as expected. 

To test:
- Update Jetpack Beta to this PR. 
Set the version number to 2.0.2 this should trigger an update to the Jetpack beta tester plugin. 
The updates happen via cron and should happen at least every 1 hour. 

- If you are running the Bleeding Edge. You should see your version update as new stuff gets pushed to the master PR. 

- If you are running a PR you should see updates happen when new stuff gets merged into the Jetpack PR. As well as when the PR gets merged into master. 

On every successful auto update an email will to the admin_user. 
emails can be turned off by adding a constant `define( 'JETPACK_BETA_SKIP_EMAIL', true );`

### CODE REVIEW

**Comment by oskosk** [comment]
testing now!

File: jetpack-beta.php [hunk 1]
```diff
@@ -857,6 +887,120 @@ static function should_update_dev_to_master() {
 		$manifest = self::get_beta_manifest();
 		return ! isset( $manifest->{$section}->{$branch} );
 	}
+
+	static function is_set_to_autoupdate() {
+		return get_option( 'jp_beta_autoupdate', false );
```
Comment (oskosk) [inline jetpack-beta.php]: I find it a little bit weird that `jp_beta_autoupdate` is used for both updating the plugin, and updating the Jetpack plugin version one is using. but it has just worked

**Comment by oskosk** [comment]
I've just realized that only tags are used for the update mechanism. I'm gonna create a tag for the latest version (2.10).

**Comment by oskosk** [comment]
* [x] Cron task works great. Updates to latest tag.
* [x] Manual update notice works great.
* [x] Mail delivery worked:
   ```
   Enabling Maintenance mode…
   Downloading update from https://github.com/Automattic/jetpack-beta/zipball/2.0.8…
   Unpacking the update…
   Installing the latest version…
   Removing the old version of the plugin…
   Plugin updated successfully.
   Disabling Maintenance mode…
   ```
* [x] Constant for skipping the email worked great.
* [ ] Autoupdate of a PR's code. _Testing now_

**Comment by oskosk** [comment]
Tested the PR and works great!

I have a question about the reported update for a PR. 

If I see `Feature Branch: update / more prop types codemod	| 5.9-beta-17479-23bff5a-update_more-prop-types-codemod`... 

What do `17479` `23bff5a` mean? They actually don't seem to represent the latest SHA for the commits there.
