### PR TITLE
Avoid errors when the plugin is installed manually.

### LINKED ISSUE #20: PHP Warnings in latest version of the plugin
```
PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /public_html/wp-includes/functions.php on line 4790
PHP Warning:  fread() expects parameter 1 to be resource, boolean given in /public_html/wp-includes/functions.php on line 4787
PHP Warning:  fopen(/public_html/wp-content/plugins/jetpack-beta/jetpack-beta.php): failed to open stream: No such file or directory in /public_html/wp-includes/functions.php on line 4784
```

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #20

When installing the plugin via the zip file generated from GitHub,
the directory name is jetpack-beta-master. We should use that naming convention in the plugin as well.

### CODE REVIEW

**Comment by enejb** [comment]
Thanks for the PR. I think we need to make this a bit more dynamic. To account for the different version of folders this plugin could be in. 
In my testing I was assuming the plugin was always in the `jetpack-beta` plugin. But I guess it depends on how folks have it installed.

**Comment by jeherve** [comment]
@enejb Good call. I've tried to make things more dynamic in 70b80d9313bf8eea61495f48e87863bb43326703

File: jetpack-beta.php [hunk 1]
```diff
@@ -35,9 +35,10 @@
  * Jetpack beta manages files inside jetpack-dev folder this folder should contain
  *
  */
-define( 'JPBETA__PLUGIN_FOLDER', plugins_url() . '/jetpack-beta/' );
+define( 'JPBETA__PLUGIN_FOLDER', plugin_dir_url( __FILE__ ) );
```
Comment (enejb) [inline jetpack-beta.php]: lets do this `define( 'JPBETA__PLUGIN_FOLDER', basename(__DIR__) );`
Since we we are not using the constant JPBETA__PLUGIN_FOLDER any where.

**Comment by jeherve** [comment]
This should work!! 🚢
